### ISSUE TITLE
Unable To Open Videos In Programs

### ISSUE THREAD

**Issue by AJ213** [noahkra/SRCModQueue#2]
**Describe the bug**
After downloading Clustertruck ILs, I am unable to open any of the files in Sony Vegas Pro or SplitRP. Something is wrong with how the mp4 files are formatted. SplitRP returns with the error "nb_frames" when trying to analyze the videos and Sony Vegas crashes or just refuses to open the file. This makes the program unusable.

**To Reproduce**
1. Search up Clustertruck
2. Filter By ILs
3. Download an IL
4. Open IL video and try to manipulate the file in a video editor or SplitRP

**Expected behavior**
It shouldn't crash programs or fail to open or analyze these files

**Additional Context**
Using something like 4k Downloader has no problem with opening the video files. SplitRP and Sony Vegas work fine with videos downloaded from this program. This will be demonstrated by verifying your desert NoUtility.

**Comment by noahkra** [comment]
Fixed in v1.1.0
