### ISSUE TITLE
Downloads Failing and No Attempt To Make Temp Files

### ISSUE THREAD

**Issue by AJ213** [noahkra/SRCModQueue#3]
**Describe the bug**
Usually when downloading a file, in the downloads folder there will be a temporary file for that file. However, right now that isn't happening. Because of this, it's impossible to delete files (as they don't exist) and it's impossible to reattempt downloading files. It's also probably impossible to download a file.

**To Reproduce**
1.  Download Selected For Anything

**Expected behavior**
I think something is wrong with how temp files are created or something along that lines. The expected behavior is it should download files.

**Screenshots**
![failed download](https://user-images.githubusercontent.com/16274000/153083620-788aaed6-0fee-482d-8c4b-f7ad8c4db5af.PNG)

**Additional context**
I have upgraded to 1.3.0 recently, but this likely happens when installing it from scratch as LoLo also had this issue.

**Comment by noahkra** [comment]
I guess this is solved now because the program no longer halts progress if it can't delete the temp files.
